[structure.py]: Refactor Center Functions
Refactor all functions that calculate specific centers of an MDAnalysis
AtomGroup.

    * Rename the `compound` argument to `cmp`, to be consistent with the
      rest of MDTools where "compound" is abbreviated by "cmp".
      Exception: The function `mdtools.structure.com` still uses
      `compound` instead of `cmp`.  Changing the argument here would
      require refactoring a lot of other code.

    * Let the `cmp` (or `compound`) argument accept the keyword
      ``'atoms'``.  If `cmp` is set to ``'atoms'``, simply return the
      atom positions.

    * Raise a warning if `debug` is set to ``True`` and the center of
      any compound is ``nan``.  Include this behavior in the docs.

    * Clarify the docs.  Especially, clarify the implications of the
      `make_whole` argument.

    * In the documentation of `mdtools.structure.coc`,
      `mdtools.structure.cog` and `mdtools.structure.com`, refer the
      reader to the documentation of `mdtools.structure.center` (-> DRY
      principle).