[pr-labeler.yml]: Disable `body-missing-regex-label`
`body-missing-regex-label` causes the pr-labeler workflow to fail with

Could not remove label "broken-template" from issue #<Number>
Error: AggregateError

Therefore, disable it.